import 'package:flutter_application_1/model/transaction.dart';

List<Transaction> sampleTransactions = [
  Transaction(
    id: '1',
    type: 'DEBIT',
    senderName: 'Alice',
    senderAccount: 'alice@upi',
    receiverName: 'Bob',
    receiverAccount: 'bob@upi',
    amount: 100.0,
    timestamp: DateTime.now().subtract(const Duration(days: 2)),
  ),
  Transaction(
    id: '2',
    type: 'DEBIT',
    senderName: 'Charlie',
    senderAccount: 'charlie@upi',
    receiverName: 'Alice',
    receiverAccount: 'alice@upi',
    amount: 50.0,
    timestamp: DateTime.now().subtract(Duration(days: 1)),
  ),
  Transaction(
    id: '3',
    type: 'DEBIT',
    senderName: 'David',
    senderAccount: 'david@upi',
    receiverName: 'Alice',
    receiverAccount: 'alice@upi',
    amount: 200.0,
    timestamp: DateTime.now(),
  ),
  Transaction(
    id: '4',
    type: 'DEBIT',
    senderName: 'Eve',
    senderAccount: 'eve@upi',
    receiverName: 'Alice',
    receiverAccount: 'alice@upi',
    amount: 75.0,
    timestamp: DateTime.now().subtract(Duration(hours: 2)),
  ),
  Transaction(
    id: '5',
    type: 'DEBIT',
    senderName: 'Frank',
    senderAccount: 'frank@upi',
    receiverName: 'Alice',
    receiverAccount: 'alice@upi',
    amount: 120.0,
    timestamp: DateTime.now().subtract(Duration(minutes: 30)),
  ),
];